apiVersion: rke-machine-config.cattle.io/v1
kind: DigitaloceanConfig
metadata:
  name: {{ .Values.cluster.name }}-nodes
  namespace: dekel-ns
region: fra1
size: {{ .Values.nodepool.size }}
sshUser: root
image: ubuntu-20-04-x64
